/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description List the adapter running in every slot.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan
         * @description Cut out and tag one garment photo. Nothing is stored.
         */
        post: operations["scan_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link
         * @description Fetch the garment image from a shop or image link, to scan a garment not owned yet.
         */
        post: operations["link_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/judge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Judge
         * @description Return BUY, SKIP or TRY_WITH for scanned tags against the owner's closet and week.
         */
        post: operations["judge_judge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/week/{owner}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Week
         * @description Return the forecast and calendar events for the coming days.
         */
        get: operations["week_week__owner__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render
         * @description Render the garment on the person.
         */
        post: operations["render_render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Ask the stylist about the current scan, verdict or closet.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/closet/{owner}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Closet
         * @description List the owner's closet.
         */
        get: operations["closet_closet__owner__get"];
        put?: never;
        /**
         * Add To Closet
         * @description Add a garment photo to the closet, tagging it unless `tags_json` is given.
         */
        post: operations["add_to_closet_closet__owner__post"];
        /**
         * Forget
         * @description Delete every garment and stored image for the owner.
         */
        delete: operations["forget_closet__owner__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/closet/{owner}/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan Closet
         * @description Find every garment in a photo of a rack or closet and add them all.
         */
        post: operations["scan_closet_closet__owner__scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/closet/{owner}/{garment_id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Garment Image
         * @description Return the stored garment cutout as PNG.
         */
        get: operations["garment_image_closet__owner___garment_id__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdapterInfo */
        AdapterInfo: {
            /** Name */
            name: string;
            /** Model */
            model?: string | null;
            /** License */
            license?: string | null;
            /** @default this_machine */
            runs_on: components["schemas"]["RunsOn"];
        };
        /** AddOut */
        AddOut: {
            garment: components["schemas"]["Garment-Output"];
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStep"][];
        };
        /** Body_add_to_closet_closet__owner__post */
        Body_add_to_closet_closet__owner__post: {
            /** Image */
            image: string;
            /**
             * Tags Json
             * @description GarmentTags as JSON; omit to auto-tag
             */
            tags_json?: string | null;
            /** Price */
            price?: number | string | null;
            /** @default closet */
            source: components["schemas"]["Source"];
            /**
             * Source Url
             * @description Shop link it came from
             */
            source_url?: string | null;
        };
        /** Body_render_render_post */
        Body_render_render_post: {
            /**
             * Person
             * @description Person photo; held in memory only
             */
            person: string;
            /**
             * Garment
             * @description Garment photo or cutout
             */
            garment: string;
            region: components["schemas"]["TryOnRegion"];
            /** Seed */
            seed?: number | null;
        };
        /** Body_scan_closet_closet__owner__scan_post */
        Body_scan_closet_closet__owner__scan_post: {
            /** Image */
            image: string;
        };
        /** Body_scan_scan_post */
        Body_scan_scan_post: {
            /** Image */
            image: string;
        };
        /** CalendarEvent */
        CalendarEvent: {
            /** Title */
            title: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** End */
            end?: string | null;
            /** Location */
            location?: string | null;
            /** Formality */
            formality?: number | null;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "top" | "sweater" | "shirt" | "outerwear" | "dress" | "bottom" | "shoes" | "accessory";
        /** ChatIn */
        ChatIn: {
            /** Owner */
            owner: string;
            /** Message */
            message: string;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["ChatTurn"][];
            candidate?: components["schemas"]["GarmentTags"] | null;
            verdict?: components["schemas"]["Verdict-Input"] | null;
            location?: components["schemas"]["Location"] | null;
        };
        /** ChatOut */
        ChatOut: {
            reply: components["schemas"]["StylistReply"];
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStep"][];
        };
        /** ChatTurn */
        ChatTurn: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "stylist";
            /** Text */
            text: string;
        };
        /** ClosetScanOut */
        ClosetScanOut: {
            /** Garments */
            garments: components["schemas"]["Garment-Output"][];
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStep"][];
        };
        /**
         * ColorFamily
         * @enum {string}
         */
        ColorFamily: "black" | "white" | "grey" | "navy" | "blue" | "green" | "yellow" | "red" | "pink" | "brown" | "beige" | "multi";
        /** DayForecast */
        DayForecast: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Temp Min C */
            temp_min_c: number;
            /** Temp Max C */
            temp_max_c: number;
            /** Precipitation Mm */
            precipitation_mm: number;
            /** Precipitation Probability */
            precipitation_probability?: number | null;
            /** Weather Code */
            weather_code?: number | null;
        };
        /**
         * Decision
         * @enum {string}
         */
        Decision: "buy" | "skip" | "try_with";
        /** Forecast */
        Forecast: {
            location: components["schemas"]["Location"];
            /** Days */
            days: components["schemas"]["DayForecast"][];
            /**
             * Attribution
             * @default Weather data by Open-Meteo.com
             */
            attribution: string;
        };
        /** ForgetOut */
        ForgetOut: {
            /** Deleted */
            deleted: number;
        };
        /**
         * Garment
         * @description A tagged garment that belongs to one owner's closet.
         */
        "Garment-Input": {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** @default closet */
            source: components["schemas"]["Source"];
            tags: components["schemas"]["GarmentTags"];
            /** Price */
            price?: number | string | null;
            /**
             * Wears
             * @default 0
             */
            wears: number;
            /** Image Ref */
            image_ref?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * Garment
         * @description A tagged garment that belongs to one owner's closet.
         */
        "Garment-Output": {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** @default closet */
            source: components["schemas"]["Source"];
            tags: components["schemas"]["GarmentTags"];
            /** Price */
            price?: string | null;
            /**
             * Wears
             * @default 0
             */
            wears: number;
            /** Image Ref */
            image_ref?: string | null;
            /** Source Url */
            source_url?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /**
         * GarmentTags
         * @description What a tagger reads off one garment image; the verdict rules see only this.
         */
        GarmentTags: {
            category: components["schemas"]["Category"];
            color_family: components["schemas"]["ColorFamily"];
            pattern: components["schemas"]["Pattern"];
            /** Warmth */
            warmth: number;
            /** Waterproof */
            waterproof: boolean;
            /** Formality */
            formality: number;
            /** Description */
            description: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Adapters */
            adapters: {
                [key: string]: components["schemas"]["AdapterInfo"];
            };
        };
        /** JudgeIn */
        JudgeIn: {
            /** Owner */
            owner: string;
            tags: components["schemas"]["GarmentTags"];
            location?: components["schemas"]["Location"] | null;
        };
        /** JudgeOut */
        JudgeOut: {
            verdict: components["schemas"]["Verdict-Output"];
            week: components["schemas"]["WeekContext"];
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStep"][];
        };
        /** LinkIn */
        LinkIn: {
            /** Url */
            url: string;
        };
        /** LinkOut */
        LinkOut: {
            /** Image Png Base64 */
            image_png_base64: string;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string | null;
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStep"][];
        };
        /** Location */
        Location: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Name */
            name?: string | null;
        };
        /**
         * Pattern
         * @enum {string}
         */
        Pattern: "solid" | "stripe" | "check" | "floral" | "graphic" | "other";
        /** PipelineStep */
        PipelineStep: {
            /** Step */
            step: string;
            adapter: components["schemas"]["AdapterInfo"];
            /** Ms */
            ms: number;
            /**
             * Touched Person Image
             * @default false
             */
            touched_person_image: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
        };
        /** Reason */
        Reason: {
            code: components["schemas"]["ReasonCode"];
            /** Message */
            message: string;
            /**
             * Garment Ids
             * @default []
             */
            garment_ids: string[];
        };
        /**
         * ReasonCode
         * @enum {string}
         */
        ReasonCode: "duplicates" | "fills_weather_gap" | "fits_event" | "statement_piece" | "pairs_well" | "few_pairings";
        /**
         * RenderAction
         * @description A stylist request to render the candidate together with these closet garments.
         */
        RenderAction: {
            /** Garment Ids */
            garment_ids: string[];
        };
        /** RenderOut */
        RenderOut: {
            /** Image Png Base64 */
            image_png_base64: string;
            /** Cached */
            cached: boolean;
            /** Fallback */
            fallback: boolean;
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStep"][];
        };
        /**
         * RunsOn
         * @description Where an adapter executes; the pipeline panel and the privacy badge read this.
         * @enum {string}
         */
        RunsOn: "this_machine" | "self_hosted_gpu" | "snowflake" | "public_api";
        /** ScanOut */
        ScanOut: {
            tags: components["schemas"]["GarmentTags"];
            /** Cutout Png Base64 */
            cutout_png_base64: string;
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStep"][];
        };
        /**
         * Source
         * @description Where a garment record came from.
         * @enum {string}
         */
        Source: "closet" | "store" | "online";
        /** StylistReply */
        StylistReply: {
            /** Text */
            text: string;
            render?: components["schemas"]["RenderAction"] | null;
        };
        /**
         * TryOnRegion
         * @description The body region a try-on model repaints.
         * @enum {string}
         */
        TryOnRegion: "upper" | "lower" | "full";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @description The rules' answer for one candidate garment; the stylist explains it, never changes it.
         */
        "Verdict-Input": {
            decision: components["schemas"]["Decision"];
            /** Headline */
            headline: string;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /**
             * Duplicates
             * @default []
             */
            duplicates: components["schemas"]["Garment-Input"][];
            /**
             * Pairings
             * @default []
             */
            pairings: components["schemas"]["Garment-Input"][];
            best_pairing?: components["schemas"]["Garment-Input"] | null;
        };
        /**
         * Verdict
         * @description The rules' answer for one candidate garment; the stylist explains it, never changes it.
         */
        "Verdict-Output": {
            decision: components["schemas"]["Decision"];
            /** Headline */
            headline: string;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
            /**
             * Duplicates
             * @default []
             */
            duplicates: components["schemas"]["Garment-Output"][];
            /**
             * Pairings
             * @default []
             */
            pairings: components["schemas"]["Garment-Output"][];
            best_pairing?: components["schemas"]["Garment-Output"] | null;
        };
        /**
         * WeekContext
         * @description The next days of weather and plans that a verdict weighs.
         */
        WeekContext: {
            forecast?: components["schemas"]["Forecast"] | null;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["CalendarEvent"][];
        };
        /** WeekOut */
        WeekOut: {
            week: components["schemas"]["WeekContext"];
            /** Pipeline */
            pipeline: components["schemas"]["PipelineStep"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    scan_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_scan_scan_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    judge_judge_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JudgeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JudgeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    week_week__owner__get: {
        parameters: {
            query?: {
                lat?: number | null;
                lon?: number | null;
            };
            header?: never;
            path: {
                owner: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_render_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_render_render_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    closet_closet__owner__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Garment-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_closet_closet__owner__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_to_closet_closet__owner__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forget_closet__owner__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForgetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_closet_closet__owner__scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_scan_closet_closet__owner__scan_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClosetScanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    garment_image_closet__owner___garment_id__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                owner: string;
                garment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
